### ISSUE TITLE
Error 'dropdown' is not a function

### ISSUE THREAD

**Issue by Amenel** [axel-zarate/js-custom-select#18]
I haven't been able to instantiate this directive in an existing project that I've joined recently because I get this error in Firebug at line 124:
`dropdownElement.eq(...).dropdown is not a function`

Are there other dependencies than the ones (AngularJS, jQuery and Bootstrap) indicated in the 
readme file? Which library is supposed to provide that "dropdown" function? Thanks.

Versions:
* Angularjs: 1.3.18
* jQuery: 2.1.4
* Bootstrap: 3.3.6
* js-custom-select: unknown, as there's no version in the file; master downloaded on 2015-12-17.

Screenshot of the Network panel in Firebug right after the error has occurred: ![js-custom-select-error](https://cloud.githubusercontent.com/assets/7868710/11897100/dfd7d5b8-a58c-11e5-82f6-cda247f7d443.png)

I've done [a quick plunk](http://plnkr.co/edit/wn5tKQtmkPPVYXJVYMWE?p=preview) and I still can't get the widget to work.

Thank you.

**Comment by axel-zarate** [comment]
Hi,
Make sure you're referencing the jQuery script before Angular. When angular loads, if jQuery is not present, it will load its implementation of jqlite, for which the jQuery plugins won't work directly.

**Comment by Amenel** [comment]
Hi, 
That was indeed the root cause of the problem. FontAwesome is also required.
Many thanks.
