### ISSUE TITLE
New release including the latest features

### ISSUE THREAD

**Issue by Amenel** [axel-zarate/js-custom-select#22]
Currently, Bower finds release 2.0.0 when asked to pull this project as a dependency. Unfortunately, that version does not seem up-to-date (in particular, it does not have support for the cs-depends-on attribute).
@axel-zarate Is it possible for you to add a new release with the current master?

**Comment by Amenel** [comment]
@axel-zarate Many thanks. We've just seen that you've published a new release many days ago. What an exceptional reactivity! Cheers.

**Comment by axel-zarate** [comment]
Yes, and I forgot to update this thread. Sorry about that. By the way, I was unaware that the bower integration was working. Good to know!
