### ISSUE TITLE
Can bind only upto 9 items

### ISSUE THREAD

**Issue by Balaji-Gopal** [axel-zarate/js-custom-select#26]
I am able to bind up-to only nine items in drop down, If I give more than that it just ignores it.

**Comment by axel-zarate** [comment]
Did you check whether that limit is imposed by any filter you might be applying? In the demo page, the second select element is bound to an array containing 59 states and they all show properly.

**Comment by Balaji-Gopal** [comment]
There is limit has been imposed,I am using it for cordova mobile application,Since the mobile device has less screen space it is rendering only up-to 9 elements only,I want to make it scrollable.

Even thought I have given the overflow:auto /overflow-x:scroll/overflow-y:scroll,I am not able to make it scrollable.
