### ISSUE TITLE
Browsify/Bower Package

### ISSUE THREAD

**Issue by pravin-d** [axel-zarate/js-custom-select#27]
Dude this seems to be a very useful library. Is there a plan to put it on browsify/bower. Would really help a lot of ppl

**Comment by axel-zarate** [comment]
I'm not a bower savvy (learning more about it is in my to-do list), but in judging by [this issue](https://github.com/axel-zarate/js-custom-select/issues/22), the plugin is available via bower. Is it missing something?

**Comment by pravin-d** [comment]
Hey thanks for the reply.. I did not find a reference in the readMe to bower. However got it through google search.  Also I was mainly wanting a browsify as it gives a good require() syntax which will be apt going forward (angularjs 2.0 and latest JS)..
