### ISSUE TITLE
Document options and callbacks that can be used

### ISSUE THREAD

**Issue by toymachiner62** [axel-zarate/js-custom-select#3]
There should be documentation on the options and callbacks that can be used. By searching through the code I was able to find that I can customize the `searchDelay` and `displayText`.

**Comment by axel-zarate** [comment]
Completed in commit [c8d13d19822e8693cf8ab75cfc1a1291211084e0](https://github.com/axel-zarate/js-custom-select/commit/c8d13d19822e8693cf8ab75cfc1a1291211084e0)

**Comment by toymachiner62** [comment]
Your options table is great. One thing i would suggest is to add the callback signature so implementers know what parameters the callback takes.
