### ISSUE TITLE
customSelect control searching its not working in customSelect.js version 2.

### ISSUE THREAD

**Issue by bhattjeet** [axel-zarate/js-custom-select#33]
Hello All,

I am using below drop down but searching functionality its not working in customSelect.js version 2.
`<div ng-model="fruit" custom-select="f for f in fruits" autofocus></div>`

Please advice me if anything was missing.

**Comment by axel-zarate** [comment]
You need to add a filter to the expression:
```html
<div ng-model="fruit" custom-select="f for f in fruits | filter: $searchTerm" autofocus></div>
```
