### ISSUE TITLE
Depended control value not updated?

### ISSUE THREAD

**Issue by bhattjeet** [axel-zarate/js-custom-select#38]
Hello All,

I have three depended custom-select control.
1) Shipper
2) Country
3) City

When i change shipper name then i fetch country and city list and assign selected id to Country and City control value  but that value is not affected.
Only country control was updated value based on shipper details. But city control value updated but its not selected.
Please see below image for more information.
![shippervalid](https://cloud.githubusercontent.com/assets/19426302/16831122/3d75d1e0-49b4-11e6-8b14-6907f0eb120a.png)

But i need like this.
![shippervalid1](https://cloud.githubusercontent.com/assets/19426302/16831150/5e46d4d2-49b4-11e6-9333-952de291265a.png)

**Comment by Amenel** [comment]
I believe you'll have a better chance of getting a quick answer if you create a Plunkr and reference it.
If both data sources are fetched at the same time, (and in the same request), I see no reason other than an error in the code for the second list to not have an item selected.

**Comment by bhattjeet** [comment]
Hello Amenel,

I will try to create Plunkar, but some how its not working.
customSelect control not working
`http://plnkr.co/edit/FK7r7OANhwDMzt2GCH5N?p=preview`
