### ISSUE TITLE
Make available via bower

### ISSUE THREAD

**Issue by toymachiner62** [axel-zarate/js-custom-select#4]
This should be made available via bower.

**Comment by axel-zarate** [comment]
I have no experience with bower. Perhaps you could help with that?

**Comment by toymachiner62** [comment]
Sure thing. (Bower)[http://bower.io/] is a package manager for client modules so rather than having to copy and paste every single file from js-custom-select into my project, I can just do a `bower install js-custom-select` for example and it pulls all the files into my project.

I'll submit a pull request for this.

**Comment by alzalabany** [comment]
.Bower.js file doesnot include a new property, so wiredep doesnot work.
please include
<pre>
"main": ["js/format.js","js/customSelect.js","css/style.css"],
</pre>
in `.brower.js` file

**Comment by asko1205** [comment]
@alzalabany I have a pull request out to make this change. Thanks! 
#16

**Comment by Amenel** [comment]
It is now made available. This should be closed.
