### ISSUE TITLE
Pre selection not working with angular-ui datepicker.

### ISSUE THREAD

**Issue by nikhil-above** [axel-zarate/js-custom-select#7]
Hi,

I am trying to use your widget with angular-ui, datepicker (https://angular-ui.github.io/bootstrap/#/datepicker). Pre  selection is not working when I add angular-ui datepicker.

```
 <input type="text" class="form-control" datepicker-popup="{{format}}" ng-model="count.dt" is-open="opened" min-date="minDate" max-date="'2015-06-22'" datepicker-options="dateOptions" date-disabled="disabled(date, mode)" ng-required="true" close-text="Close" />
<div custom-select id="id_plu" class="required" name="plu" ng-model="count.plu" ng-options="plu.id for plu in plu_list" >
```

**Comment by axel-zarate** [comment]
Hello,

Can you provide a fiddle where you replicate the issue?

Thanks.

**Comment by axel-zarate** [comment]
If you are using Angular 1.4 or greater, chances are that the initial value is not being shown in the view. You can try with the version in [this branch](https://github.com/axel-zarate/js-custom-select/tree/promises). A few things have changed here and eventually this will be moved into the master branch.

Regards.

**Comment by axel-zarate** [comment]
Closed due to inactivity.
